services:
  - type: web
    name: game-catalog
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd djangoApp/gameCatalog && gunicorn gameCatalog.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true



